# Generated by Django 2.1.4 on 2019-01-20 01:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='cowork',
            name='lon',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='cowork',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='cowork',
            name='current_coworkers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
