site_name: birdman
site_description: groundbreaker, icebreaker
repo_url: https://github.com/hidalgopl/birdman
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/hidalgopl">hidalgopl</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
