global:
  owner: bojan

replicas: 1

image:
  name: gis-service
  pullPolicy: "IfNotPresent"

resources:
  limits:
    cpu: 2
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

lowResources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 0.05
    memory: 64Mi
