# Generated by Django 2.1.4 on 2019-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='lon',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
    ]
