# Generated by Django 2.1.5 on 2019-03-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservisit',
            options={'ordering': ('-created',)},
        ),
    ]
