# Generated by Django 2.1.4 on 2019-01-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[('PERSON', 0), ('ORG', 1)], default=0, verbose_name='user_type'),
        ),
    ]
